#!/usr/bin/env bash
#
# TWG Security — regenerate checksums.txt for the pinned NX packages
# ------------------------------------------------------------------
# Downloads both pinned .deb packages (Witness + Meta), computes their
# SHA256 sums, and writes checksums.txt in `sha256sum` format:
#
#     <64-hex-hash>  <filename>
#
# Run this manually whenever the pinned NX build changes. Keep the pinned
# version here in lockstep with install.sh, then commit the updated
# checksums.txt.
#
# Usage:
#   ./make-checksums.sh

set -euo pipefail

# ---------------------------------------------------------------------------
# Pinned NX release — keep in sync with install.sh
# ---------------------------------------------------------------------------
NX_VERSION="6.1.2"
NX_BUILD="42921"

# Pinned download URLs (same as install.sh).
WITNESS_URL="https://updates.networkoptix.com/default/${NX_BUILD}/linux/nxwitness-server-${NX_VERSION}.${NX_BUILD}-linux_x64.deb"
META_URL="https://updates.networkoptix.com/metavms/${NX_BUILD}/linux/metavms-server-${NX_VERSION}.${NX_BUILD}-linux_x64.deb"

# Resolve paths relative to this script so it works from any CWD.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="${SCRIPT_DIR}/checksums.txt"

# Temp workspace with guaranteed cleanup.
WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

echo ">>> Regenerating checksums for NX ${NX_VERSION} build ${NX_BUILD}"

# Download each package, then hash it. We hash from within WORKDIR so the
# second column of sha256sum output is the bare filename, not a path.
for URL in "${WITNESS_URL}" "${META_URL}"; do
  FILE="$(basename "${URL}")"
  echo ">>> Downloading ${FILE}"
  curl -fSL --retry 3 --retry-delay 2 -o "${WORKDIR}/${FILE}" "${URL}"
done

echo ">>> Computing SHA256 sums"
# Header comment lines start with '#'; install.sh only reads rows whose first
# field is a 64-hex hash, so comments are ignored on read.
{
  echo "# TWG Security — NX package checksums"
  echo "# NX ${NX_VERSION} build ${NX_BUILD}"
  echo "# Generated by make-checksums.sh — do not edit by hand."
  ( cd "${WORKDIR}" && sha256sum ./*.deb | sed 's# \./# #' )
} > "${OUT_FILE}"

echo ">>> Wrote ${OUT_FILE}:"
cat "${OUT_FILE}"
